#!/usr/bin/env python3.5
# vimb-bookmark [dmenu-command]
#
# Open dmenu-selected URLs from vimb bookmarks.
#
# Note: dmenu must be line-buffered (eg. "stdbuf --output=L dmenu ..." on Linux) if you want multiple selections (ctrl+return) to start immediately.

import os
import re
import subprocess
import sys

def main(args):
    if not args:
        args = ["dmenu"]
    filename = (os.environ.get("XDG_CONFIG_HOME") or os.environ["HOME"] + "/.config") + "/vimb/bookmark"
    with open(filename) as f, popen(args) as dmenu:
        for line in f:
            line = line.rstrip()
            if line.startswith("#"):
                continue
            if not line:
                dmenu.stdin.write("\n")
                continue
            line = re.sub(" {2,}", " ", line)

            url, _, rest = line.partition("\t")
            url = url.strip()
            title, _, tags = rest.partition("\t")
            title = title.strip()
            tags = tags.strip().split(" ")

            if title:
                out = title
            else:
                out = ""
            if tags:
                out += " [" + " ".join("#" + x for x in tags) + "]"
            dmenu.stdin.write("{}  ({})\n".format(out, url))
        dmenu.stdin.close()
        seen = {""}
        for x in iter(dmenu.stdout.readline, ""):
            if "  (" in url:
                url = x.rstrip().partition("  (")[2][:-1]
            elif url.partition("://")[0] not in ("http", "https", "file", "ftp"):
                url = "http://" + url
            if url not in seen:
                seen.add(url)
                os.spawnvp(os.P_NOWAIT, "vimb", ["vimb", url])

def popen(*args, **kwds):
    assert "stderr" not in kwds
    return subprocess.Popen(*args, bufsize=1, universal_newlines="\n", stdin=subprocess.PIPE, stdout=subprocess.PIPE, **kwds)

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
